---
# tasks file for devops_demo
- name: "Install the Package"
  apt:
    name: nginx
    state: present
- name: "Stop service"
  service:
    name: nginx
    state: stopped
- name: "Update Configurations"
  template:
    src: port.j2
    dest: /etc/nginx/sites-enabled/default
- name: "Start service"
  service:
    name: nginx
    state: started
#- name: "Stop service"
#  service:
#    name: nginx
#    state: stopped
#- name: "Remove the Package"
#  apt:
#    name: nginx
#    state: absent